### ISSUE TITLE
Add toml support for Configurate

### ISSUE THREAD

**Issue by iceBear67** [kalculos/dash#32]
Currently, dash is using Jackson for TOML (de)serialization, and there are some existing implementations of TOML support for configurate. However, these implementations don't use Jackson, they use TOMLJ instead. 

The existing configurate-Jackson can be a great example for assignees.

Create a new repository to do this.

**Comment by iceBear67** [comment]
@EvanLuo42 how is it going?

**Comment by EvanLuo42** [comment]
> @EvanLuo42 how is it going?

In progress

**Comment by iceBear67** [comment]
please tell me your progress

**Comment by EvanLuo42** [comment]
> please tell me your progress

I don't know what do you mean by using Jackson to implement. Isn't Jackson only for Json?

**Comment by iceBear67** [comment]
By simply check the repository you'll find that there are many dataformat supports in Jackson.

**Comment by iceBear67** [comment]
and TOML is one of them, what you need to do is make some patches for `TomlMapper` and `TomlFactory` etc, I think

**Comment by EvanLuo42** [comment]
> what is going on

月考ing

**Comment by iceBear67** [comment]
huh  you are busier than me

**Comment by qyl27** [comment]
Assign received, configurate is the one by SpongePowered?  
I haven't heard about Jackson for TOML.

**Comment by iceBear67** [comment]
https://github.com/FasterXML/jackson-dataformats-text/tree/2.13/toml

**Comment by iceBear67** [comment]
Ctrl+F won't hurt you.

**Comment by qyl27** [comment]
I will do it in several days.

**Comment by qyl27** [comment]
https://github.com/qyl27/Configurate-TOML
A simpleimplementation with some known issues.
